name: Let's try to build ScanTailor

on:
  workflow_dispatch:
  
env:
  ST_GIT: https://github.com/4lex4/scantailor-advanced.git
  WORKDIR: scantailor
  BUILDDIR: build
  
jobs:
  compile:
    runs-on: ubuntu-22.04
    
    steps:
  
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install gcc g++ cmake libjpeg-dev libpng-dev \
          libtiff5 libtiff5-dev libboost-test-dev \
          qtbase5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools \
          libqt5opengl5-dev libpthread-stubs0-dev
  
    - name: Check it out
      run: |
        git clone ${{ env.ST_GIT }} ${{ env.WORKDIR }}
        
    - name: Prepare it
      working-directory: ${{ env.WORKDIR }}
      run: |
        mkdir {{ env.BUILDDIR }}

    - name: Build it
      working-directory: ${{ env.WORKDIR }}/{{ env.BUILDDIR }}
      run: |
        cmake -G "Unix Makefiles" ..
        cmake --build .
        make
      
    - name: Pack it
      working-directory: ${{ env.WORKDIR }}/{{ env.BUILDDIR }}
      run: |
        cpack -G "DEB"

    - name: Test it
      working-directory: ${{ env.WORKDIR }}/{{ env.BUILDDIR }}
      run: |
        pwd
        ls -lh
        sudo apt-get install ./*.deb
        
    - name: Keep it
      run: |
        uses: actions/upload-artifact@v3
        with:
          name: scantailor.deb
          path: ${{ github.workspace }}/${{ env.WORKDIR }}/{{ env.BUILDDIR }}/*.deb
          retention-days: 3
