name: Let's try to build ScanTailor

on:
  workflow_dispatch:
  
jobs:
  compile:
    runs-on: ubuntu-22.04
    
    steps:
  
    - name: Install deps
      run: |
        apt-get update
        apt-get upgrade
        apt-get install gcc g++ cmake libjpeg-dev libpng-dev \
          libtiff5 libtiff5-dev libboost-test1.63-dev libboost-test1.63.0 \
          qtbase5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools \
          libqt5opengl5-dev libpthread-stubs0-dev git
  
