name: Let's try to build ScanTailor

on:
  workflow_dispatch:
  
jobs:
  compile:
    runs-on: ubuntu-22.04
    
    steps:
  
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install gcc g++ cmake libjpeg-dev libpng-dev \
          libtiff5 libtiff5-dev libboost-test-dev \
          qtbase5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools \
          libqt5opengl5-dev libpthread-stubs0-dev
  
